### ISSUE TITLE
Manage existing workdirs

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#13]
Right now you can change your active workdir. But you can't list all the dirs for which you already have data.

We need to define if this will be a command to list existing workdirs, or just a matter of adding to the docs that you can peek into `~/.srcd/workdirs`.

Related to this, you can `prune` existing data for the current active workdir, but this will not clean the data for other workdirs.

**Comment by dpordomingo** [comment]
I'd vote for a proper list command from `sourced` command itself.
Also, imo there should be a `prune --all` option, to clean all working dirs; wouldn't it be useful?

**Comment by carlosms** [comment]
> Also, imo there should be a `prune --all` option, to clean all working dirs; wouldn't it be useful?

Yes, something like this is what I had in mind.

**Comment by dpordomingo** [comment]
As a user, I'd like to have such listing command to see available workdirs.

As far as I understand, the way to list all the inited dirs would be to glob `~/.srcd/workdirs/**/.env`, then to read their `GITBASE_REPOS_DIR` value, and cross the fingers to ensure that the user didn't modify/delete/add whatever directory or docker container.
Should we proceed with this approach?
If we do so, we could use it to `prune --all`; otherwise, the `prune --all` could delete "every docker resource called `srcd-*`, but I think it's really ugly.

Imo `sourced` should provide a more consistent and fault tolerant way to register and un-register workdirectories, but it would require more effort.

wdyt?

**Comment by carlosms** [comment]
> Imo `sourced` should provide a more consistent and fault tolerant way to register and un-register workdirectories, but it would require more effort.
> 
> wdyt?

I'm open to discuss any proposals for improvements you may have, maybe over slack or next team meeting. But let's keep in mind `sourced` is supposed to be a light wrapper around docker compose.
