### ISSUE TITLE
Invalid interpolation format for "environment" option in service "ghsync": "${GITHUB_TOKEN:-}"

### ISSUE THREAD

**Issue by jeroenherczeg** [src-d/sourced-ce#167]
Hi,

I downloaded `sourced-ce_v0.14.0-rc.1_linux_amd64`.

When I run I receive this error
```
$ ./sourced init local /home/kesshi/repositories

/home/kesshi/.sourced does not exist
Cannot perform this action, source{d} needs to be initialized first with the 'init' sub command
```

After I created `/home/kesshi/.sourced`, I run `./sourced init local /home/kesshi/repositories` again and receive this error

```
$ ./sourced init local /home/kesshi/repositories

ERROR: Invalid interpolation format for "environment" option in service "ghsync": "${GITHUB_TOKEN:-}"

docker-compose working directory set to /home/kesshi/.sourced/workdirs/home/kesshi/repositories

Builds, (re)creates, starts, and attaches to containers for a service.

Unless they are already running, this command also starts any linked services.

The `docker-compose up` command aggregates the output of each container. When
the command exits, all containers are stopped. Running `docker-compose up -d`
starts the containers in the background and leaves them running.

If there are existing containers for a service, and the service's configuration
or image was changed after the container's creation, `docker-compose up` picks
up the changes by stopping and recreating the containers (preserving mounted
volumes). To prevent Compose from picking up changes, use the `--no-recreate`
flag.

If you want to force Compose to stop and recreate all containers, use the
`--force-recreate` flag.

Usage: up [options] [--scale SERVICE=NUM...] [SERVICE...]

Options:
    -d                         Detached mode: Run containers in the background,
                               print new container names.
                               Incompatible with --abort-on-container-exit.
    --no-color                 Produce monochrome output.
    --no-deps                  Don't start linked services.
    --force-recreate           Recreate containers even if their configuration
                               and image haven't changed.
                               Incompatible with --no-recreate.
    --no-recreate              If containers already exist, don't recreate them.
                               Incompatible with --force-recreate.
    --no-build                 Don't build an image, even if it's missing.
    --no-start                 Don't start the services after creating them.
    --build                    Build images before starting containers.
    --abort-on-container-exit  Stops all containers if any container was stopped.
                               Incompatible with -d.
    -t, --timeout TIMEOUT      Use this timeout in seconds for container shutdown
                               when attached or when containers are already
                               running. (default: 10)
    --remove-orphans           Remove containers for services not
                               defined in the Compose file
    --exit-code-from SERVICE   Return the exit code of the selected service container.
                               Implies --abort-on-container-exit.
    --scale SERVICE=NUM        Scale SERVICE to NUM instances. Overrides the `scale`
                               setting in the Compose file if present.
exit status 1
```

**Comment by dpordomingo** [comment]
First issue is dupe of https://github.com/src-d/sourced-ce/issues/160 whose fix is already being reviewed and will hopefully be merged soon.

I'll dig more about the rest of what you reported.

**Comment by carlosms** [comment]
About the interpolation format error, is your github token a normal alphanumeric string, without any spaces or symbols?

**Comment by jeroenherczeg** [comment]
I haven’t added a github token. Didn’t see it mentioned in the docs.

**Comment by dpordomingo** [comment]
it is not needed if you're initializing with `sourced init local`

**Comment by carlosms** [comment]
Oops, my bad, locally there should be no `GITHUB_TOKEN`.

Can you please share the output of `docker-compose -v` and the contents of `~/.sourced/workdirs/__active__/.env` and `~/.sourced/workdirs/__active__/docker-compose.yml`?

**Comment by dpordomingo** [comment]
The fix for the first issue was already released by [sourced-ce v0.14.0-rc.2](https://github.com/src-d/sourced-ce/releases/tag/v0.14.0-rc.2).

Let us know about the info requested by [:point_up: issuecomment-516368609](https://github.com/src-d/sourced-ce/issues/167#issuecomment-516368609)

If there's nothing weird there, I'd say that the problem could be caused by how the environment variables are interpreted in your PC; what this returns?

```shell
uname -a
echo $0
```

**Comment by jeroenherczeg** [comment]
Thanks guys for your work
This is my .sourced directory:
https://github.com/jeroenherczeg/.sourced

I remove my github token, so the one in the env file is not valid anymore.

`.sourced git:(master) uname -a
Linux hadary 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

`.sourced git:(master) echo $0
zsh
`

**Comment by dpordomingo** [comment]
Sorry, but I tried hard and I could not reproduce your bug.

That's what I did:
- loged in `zsh`
- changed my home to a brand new `/home/kesshi` (pretending to be you)
- added a couple of git repos into `/home/kesshi/repositories`
- downloaded `sourced v0.14.0-rc.1` for Linux
- ran `./sourced init local /home/kesshi/repositories` &rarr; which failed as you saw (expected)
- created `/home/kesshi/.sourced`
- ran (again) `./sourced init local /home/kesshi/repositories` &rarr; which succeeded (you failed)
- ran `./sourced init orgs protoku --token=HIDDEN` &rarr; which succeeded
- ran (again) `./sourced init local /home/kesshi/repositories` &rarr; which succeeded (you failed)

All what I tried, worked as expected, so I could not reproduce your problem.

I thought that maybe you edited something in `~/.sourced`, so I compared yours (from [your repo](https://github.com/jeroenherczeg/.sourced)), with the one that was generated while I was trying to reproduce the issue, but I saw that your config and my config was exactly the same (but the gh token, obviously).
```shell
% git clone git@github.com:jeroenherczeg/.sourced.git .sourced-jeroenherczeg
% rm -rf .sourced-jeroenherczeg/.git .sourced-jeroenherczeg/sourced
% diff --recursive .sourced .sourced-jeroenherczeg
diff --recursive .sourced/workdirs/cHJvdG9rdQ==/.env .sourced-jeroenherczeg/workdirs/cHJvdG9rdQ==/.env
6c6
< 	GITHUB_TOKEN=HIDDEN
---
> 	GITHUB_TOKEN=dad197661c6fa3654151e0126f99668e0cd1c176
```


...
so... could you please ensure that no docker container from `sourced` is running, remove `~/.sourced`, download the new release `sourced v0.14.0-rc.2`, and try again with `sourced init local /home/kesshi/repositories` and let us know if the bug is still there?

**Comment by jeroenherczeg** [comment]
Success!

`docker-compose -v
docker-compose version 1.17.1, build unknown`

I have no clue why I had such an out-dated version of docker-compose, but I updated to 1.24.1 and it worked.

Thanks guys for the help and awesome product!
