### ISSUE TITLE
Set SOURCED_GITHUB_TOKEN on travis

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/sourced-ce#187]
Some integration tests are currently being skipped on travis as the `SOURCED_GITHUB_TOKEN` env var is not set.

**Comment by carlosms** [comment]
It is set: https://github.com/src-d/sourced-ce/blob/master/.travis.yml#L16

but travis only exports the secret keys to the build if the PR comes from a repo branch. To trigger all tests for a PR we need to push to a branch in this repo instead of our forks.
The tests for master do not skip any of the integration tests.

**Comment by se7entyse7en** [comment]
Oh ok! I didn't know that, and I actually missed to take a look at the travis file. Thanks!
