### ISSUE TITLE
Add docs to build from sources

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#26]
The docs should be clear enough that can be copy-pasted.
It should include details on how to run:
- a modified docker-compose file, optional if needed
- a sourced-ui built locally, optional if needed

**Comment by dpordomingo** [comment]
When **incubator-superset** is ran in development mode, it's usually started with local directories binded to some internal paths. Content from volumes &mdash;in linux&mdash;, is owned by the user from the host machine.
Since the **incubator-superset** container is built to be run with `superset` user, content from volumes might be not writable because `superset` user is not the owner of those mounted dirs (as described by https://github.com/apache/incubator-superset/issues/6887).


Alternatives:

Run **incubator-superset** as `root`:
  - since it's not the expected way to run superset, it can be unexpected,
  - data writen in the volumes (as `__pycache__` or `node_modules`) will be writen as `root`, so it won't be writable from the host machine (without being `root`)

Run **incubator-superset** container as `root`, but run **incubator-superset** app with the user owning the binded data; to do so:
  1. **assumption:** all the binded data is owned by the same user.
  1. Change the uid of `superset`, to the uid of the owner of the binded data.
  1. Make sure the entrypoint is run by `superset` user, owning the original container data and the data binded to directories in the host machine.
  1. All the data writen by `superset`, will use the uid of the user of the host, so it will be writable also by that user in the host.


Docker loads (by default) an extra `docker-compose.override.yml` file (docs [_multiple-compose-files_](https://docs.docker.com/compose/extends/#understanding-multiple-compose-files)), whith that in mind, we can extend our official `docker-compose.yml` file with our custom config to let the user run **source{d} CE** in development mode with hot reloading.
