### ISSUE TITLE
Changelog looks bad on gitbook

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#65]
Probably it's best to hide it.
https://docs.sourced.tech/community-edition

**Comment by dpordomingo** [comment]
I think it's a good idea to show the Changelog in our docs (which is a common thing in the industry)

The problem is that GitBook does not support HTML code (only plain Markdown), so the HTML tag `<details>`, used to collapse the unreleased changes, is not supported.

Since we already agreed on avoiding HTML code, I'd purpose some alternatives:
- separate the unreleased changes into a new file, example: `Changelog.unreleased.md`, or
- since the unreleased section could not be collapsed, move it to the bottom of the CHANGELOG file.

For both alternatives, we could add a link to the unreleased changes in the top section of the original Changelog.

wdyt?

**Comment by carlosms** [comment]
Let's think about more permanent solutions in the next iterations.
For this very first release let's just hide it.

**Comment by dpordomingo** [comment]
Already hidden in my pr

**Comment by dpordomingo** [comment]
People from DP just show the unreleased stuff as another item, i.e. [src-d/gitbase/CHANGELOG.md](https://github.com/src-d/gitbase/blob/ade8efccee0cf097be57da683bda229129d042d7/CHANGELOG.md)
I'd vote for that.
